
spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:tc:mysql:latest:///indulge
    username: root
    password: Shelah2020

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false


