
#spring:
#  sql:
#    init:
#      mode: always
#  datasource:
#    url: jdbc:mysql://localhost:3306/indulge_test
#    username: root
#    password: s3cret
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    open-in-view: false




spring:
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=MYSQL
#    username: sa
#    password: sa
    url: jdbc:tc:mysql:latest:///indulge_test
    username: duke
    password: s3cret

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
      #properties:
    #hibernate:
    #enable_lazy_load_no_trans: true

  # ===============================
  # = MAIL
  # ===============================

  mail:
    host: smtp.gmail.com
    password: mydevemail20201#
    username: mydevemail2020@gmail.com
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true
            required: true


server:
  port: ${PORT:5001}
  servlet:
    context-path: /indulge
api:
  url-domain: http://localhost:5001${server.servlet.context-path}




